:toc:
:toc-placement!:

:icons: font

Here is my preamble paragraph, but I could really place the TOC anywhere! Lorem ipsum foo bar baz.

More details here :
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74


toc::[]


= Document Title (Level 0)

== Level 1 Section Title

=== Level 2 Section Title

==== Level 3 Section Title

===== Level 4 Section Title

====== Level 5 Section Title

== Another Level 1 Section Title



[NOTE]
====
A sample note admonition.
We can use gemoji icons in the Asciidoctor markup.
We assign an icon name to the document
attributes `tip-caption`, `note-caption` and `important-caption`.
====

TIP: It works!

IMPORTANT: Asciidoctor is awesome, don't forget!

CAUTION: Don't forget to add the `...-caption` document attributes in the header of the document on GitHub.

WARNING: You have no reason not to use Asciidoctor.


[source,groovy]
----
package com.mrhaki.adoc

class Sample {
    String username // <1>

    String toString() {
        "${username?.toUpperCase() ?: 'not-defined'}" // <2>
    }
}
----
<1> Simple property definition where Groovy will generate the +setUsername+ and +getUsername+ methods.
<2> Return username in upper case if set, otherwise return +not-defined+.


