=== Fault Tolerance 1.0
The Fault Tolerance API gives you powerful features that solves typical issues dealing with latency and fault tolerance in distributed systems like MicroServices.

The functionality is similar as that found in popular 3rd party libraries as https://github.com/Netflix/Hystrix[Hystrix], but much easier to use.

Most of the functionality can be combined, so that a timeout or bulkhead issue could trigger a fallback value.

==== Retry
Using a simple annotations you can define criteria for how often and when to retry.

The example code for this feature is rigged for max 4 tries before failing (the original call + three retries).
You control the number of attempts before simulating success.
```
curl -i http://localhost:8080/payaramicro/rest/faulttolerance/retry/1
Expected return is HTTP 200 : This is try 1, returning success

curl -i http://localhost:8080/payaramicro/rest/faulttolerance/retry/4
Expected return is HTTP 200 : This is try 4, returning success

curl -i http://localhost:8080/payaramicro/rest/faulttolerance/retry/9
Expected return is HTTP 400 : We just got RuntimeException of type 'IllegalStateException'.
```

==== Timeout
Define a duration for timeout that will abandon the execution.
Very useful in combination with fallback.

The code example will timeout and abandon execution after 1000ms.
```
curl -i http://localhost:8080/payaramicro/rest/faulttolerance/timeout/500
Expected HTTP 200 : Function simulated work for 500ms.

curl -i http://localhost:8080/payaramicro/rest/faulttolerance/timeout/1500
Expected HTTP 400 : We just got RuntimeException of type 'TimeoutException'.
```

[NOTE]
The ExceptionMapperUnhandled eats all RunTimeExceptions (including TimeoutException) and maps to HTTP 400 and a text message.

==== Fallback
When execution fails you can provide an alternative method that should return a value.
Useful to prevent system from failing and continue with some default or cached data.

The code example will timeout after 1000ms and return an alternative value instead.
```
curl -i http://localhost:8080/payaramicro/rest/faulttolerance/fallback/500
Expected HTTP 200 : Function simulated work for 500ms.

curl -i http://localhost:8080/payaramicro/rest/faulttolerance/fallback/1500
Expected HTTP 200 : Timeout was exceeded, we return this fallback text instead.
```

[NOTE]
The method providing the alternative value must have the same CDI scope,
be public and have the same input and return types.

==== Bulkhead
Bulkhead isolates faults in one part of the system from cascading out of control.
If solved this by limiting the number of concurrent requests to a resource.

The code example limits the concurrency to 2 executions, the third will trigger exeption.
```
curl -i http://localhost:8080/payaramicro/rest/faulttolerance/bulkhead/5000
Expected HTTP 200 : Function simulated work for 5000ms.

Now do the same from 3 command line windows and you'll see that the last one will fail like this :
Expected HTTP 400 : We just got RuntimeException of type 'BulkheadException'.
```
[NOTE]
The ExceptionMapperUnhandled eats all RunTimeExceptions (including BulkheadException) and maps to HTTP 400 and a text message.

More documentation at https://microprofile.io/project/eclipse/microprofile-fault-tolerance/spec/src/main/asciidoc/bulkhead.asciidoc[Bulkhead documentation].

==== Circuit Breaker
Allows system to fail fast after detecting a failure.
When a failing resource is detected additional requests will fail instantly.

The code example will break the circuit when 3 out of 4 calls fails (failureRatio 0.75).
After 15 seconds the circuit will go into half-closed mode and allow new calls.
After 5 successful calls in half-closed mode the circuit returns to permanent closed mode.

```
Try one call that does not force exception :
curl -i http://localhost:8080/payaramicro/rest/faulttolerance/circuitbreaker/false
Expect HTTP 200 and a response text.

Now try 6 calls in a row that force a failure :
curl -i http://localhost:8080/payaramicro/rest/faulttolerance/circuitbreaker/true
Expect the first 3 to fail with IllegalStateException and the remaining to fail with CircuitBreakerOpenException.

Immediately continue with multiple calls that does not force exception :
curl -i http://localhost:8080/payaramicro/rest/faulttolerance/circuitbreaker/false
Expect them to continue to fail with CircuitBreakerOpenException unit circuit has been open for 15 seconds.

When circuit is closed again you can force some more failures and verify that the circuit will break once more.
```

