:toc:
:toclevels: 3
:toc-placement!:

= Payara Micro Playground

This project demonstrate different JEE features using Payara Micro.

Each chapter corresponds to a Java code package with the same name
that aims to demonstrate and describe one feature.

All code is standard JEE7 or MicroProfile and should easily run on JEE servers like
https://www.payara.fish/payara_micro[Payara Micro],
http://wildfly-swarm.io[WildFly Swarm],
http://tomee.apache.org[TomEE] and
https://openliberty.io[OpenLiberty].

It should also work great with module based runtimes as
https://ee.kumuluz.com[kumuluzEE] and
https://hammock-project.github.io[Hammock].

toc::[]

== How to build and run
This is documented in README.md

== How to use JEE7 features
This chapter describes different JEE7 features, see the corresponding
Java source packages for code.

include::database.adoc[]

include::events.adoc[]

include::exceptions.adoc[]

include::jaxrs.adoc[]

include::jpa.adoc[]

include::security.adoc[]

== How to use MicroProfile 1.3 features
These features are yet to be included in the playground `JWT Propagation 1.0`,
`Health Metrics 1.0`, `Health Check 1.0`.

include::config.adoc[]

include::faulttolerance.adoc[]

include::metrics.adoc[]

include::openapi.adoc[]

== How to use JCache features
When running Payara Micro in cluster mode you have cluster aware caching available for free.

include::cache.adoc[]

== More adoc examples
Here are some more adoc examples.

include::adoc.adoc[]
